### ISSUE TITLE
Unsupported class file major version 61 under Java 17

### ISSUE THREAD

**Issue by stefanomioli-centropaghe** [daniel-frak/keycloak-user-migration#61]
Hello, what Java version are we supposed to use to compile this plugin?

I'm not a Java guy by any means, so apologies if this is a dumb question, but I haven't seen it mentioned anywhere in the docs.

I'm getting `Unsupported class file major version 61` when executing the tests with these versions of Java and Maven:

```
> java --version
java 17.0.3.1 2022-04-22 LTS
Java(TM) SE Runtime Environment (build 17.0.3.1+2-LTS-6)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.3.1+2-LTS-6, mixed mode, sharing)

> mvn --version
Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
Maven home: d:\dev\bin\apache-maven-3.8.5
Java version: 17.0.3.1, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-17.0.3.1
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```
Here's the full build log:

```
> .\mvnw.cmd clean package
[INFO] Scanning for projects...
[INFO]
[INFO] ---< com.danielfrak.code.keycloak.providers:keycloak-rest-provider >----
[INFO] Building keycloak-rest-provider 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ keycloak-rest-provider ---
[INFO] Deleting D:\dev\keycloak-cp-theme\keycloak-user-migration\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ keycloak-rest-provider ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ keycloak-rest-provider ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 12 source files to D:\dev\keycloak-cp-theme\keycloak-user-migration\target\classes
[WARNING] /D:/dev/keycloak-cp-theme/keycloak-user-migration/src/main/java/com/danielfrak/code/keycloak/providers/rest/LegacyProvider.java: D:\dev\keycloak-cp-theme\keycloak-user-migration\src\main\java\com\danielfrak\code\keycloak\providers\rest\LegacyProvider.java uses or overrides a deprecated API.
[WARNING] /D:/dev/keycloak-cp-theme/keycloak-user-migration/src/main/java/com/danielfrak/code/keycloak/providers/rest/LegacyProvider.java: Recompile with -Xlint:deprecation for details.
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ keycloak-rest-provider ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory D:\dev\keycloak-cp-theme\keycloak-user-migration\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ keycloak-rest-provider ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 12 source files to D:\dev\keycloak-cp-theme\keycloak-user-migration\target\test-classes
[WARNING] /D:/dev/keycloak-cp-theme/keycloak-user-migration/src/test/java/com/danielfrak/code/keycloak/providers/rest/remote/TestUserModel.java: D:\dev\keycloak-cp-theme\keycloak-user-migration\src\test\java\com\danielfrak\code\keycloak\providers\rest\remote\TestUserModel.java uses or overrides a deprecated API.
[WARNING] /D:/dev/keycloak-cp-theme/keycloak-user-migration/src/test/java/com/danielfrak/code/keycloak/providers/rest/remote/TestUserModel.java: Recompile with -Xlint:deprecation for details.
[INFO]
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ keycloak-rest-provider ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.danielfrak.code.keycloak.providers.rest.ConfigurationPropertiesTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.07 s - in com.danielfrak.code.keycloak.providers.rest.ConfigurationPropertiesTest
[INFO] Running com.danielfrak.code.keycloak.providers.rest.exceptions.RestUserProviderExceptionTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 s - in com.danielfrak.code.keycloak.providers.rest.exceptions.RestUserProviderExceptionTest
[INFO] Running com.danielfrak.code.keycloak.providers.rest.LegacyProviderFactoryTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.832 s - in com.danielfrak.code.keycloak.providers.rest.LegacyProviderFactoryTest
[INFO] Running com.danielfrak.code.keycloak.providers.rest.LegacyProviderTest
giu 08, 2022 9:15:50 AM com.danielfrak.code.keycloak.providers.rest.LegacyProvider lambda$getUserModel$2
WARN: User not found in external repository: user
giu 08, 2022 9:15:50 AM com.danielfrak.code.keycloak.providers.rest.LegacyProvider lambda$getUserModel$2
WARN: User not found in external repository: user
[INFO] Tests run: 17, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.372 s - in com.danielfrak.code.keycloak.providers.rest.LegacyProviderTest
[INFO] Running com.danielfrak.code.keycloak.providers.rest.remote.LegacyUserTest
[ERROR] Tests run: 11, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.102 s <<< FAILURE! - in com.danielfrak.code.keycloak.providers.rest.remote.LegacyUserTest
[ERROR] testEquals  Time elapsed: 0.098 s  <<< FAILURE!
java.lang.AssertionError:
EqualsVerifier found a problem in class com.danielfrak.code.keycloak.providers.rest.remote.LegacyUser.
-> Unsupported class file major version 61

For more information, go to: https://www.jqno.nl/equalsverifier/errormessages
        at com.danielfrak.code.keycloak.providers.rest.remote.LegacyUserTest.testEquals(LegacyUserTest.java:95)
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 61
        at com.danielfrak.code.keycloak.providers.rest.remote.LegacyUserTest.testEquals(LegacyUserTest.java:95)

[INFO] Running com.danielfrak.code.keycloak.providers.rest.remote.UserModelFactoryTest
giu 08, 2022 9:15:51 AM com.danielfrak.code.keycloak.providers.rest.remote.UserModelFactory create
INFO: Creating user model for: user
giu 08, 2022 9:15:51 AM com.danielfrak.code.keycloak.providers.rest.remote.UserModelFactory create
INFO: Creating user model for: user
giu 08, 2022 9:15:51 AM com.danielfrak.code.keycloak.providers.rest.remote.UserModelFactory lambda$getGroupModel$6
INFO: Found existing group group with id 12345
giu 08, 2022 9:15:51 AM com.danielfrak.code.keycloak.providers.rest.remote.UserModelFactory create
INFO: Creating user model for: user
giu 08, 2022 9:15:51 AM com.danielfrak.code.keycloak.providers.rest.remote.UserModelFactory create
INFO: Creating user model for: user
giu 08, 2022 9:15:51 AM com.danielfrak.code.keycloak.providers.rest.remote.UserModelFactory create
INFO: Creating user model for: user
giu 08, 2022 9:15:51 AM com.danielfrak.code.keycloak.providers.rest.remote.UserModelFactory lambda$getGroupModel$7
INFO: Created group null with id null
giu 08, 2022 9:15:51 AM com.danielfrak.code.keycloak.providers.rest.remote.UserModelFactory lambda$getGroupModel$7
INFO: Created group null with id null
giu 08, 2022 9:15:51 AM com.danielfrak.code.keycloak.providers.rest.remote.UserModelFactory create
INFO: Creating user model for: user
giu 08, 2022 9:15:51 AM com.danielfrak.code.keycloak.providers.rest.remote.UserModelFactory create
INFO: Creating user model for: user
giu 08, 2022 9:15:51 AM com.danielfrak.code.keycloak.providers.rest.remote.UserModelFactory create
INFO: Creating user model for: user
giu 08, 2022 9:15:51 AM com.danielfrak.code.keycloak.providers.rest.remote.UserModelFactory create
INFO: Creating user model for: user
giu 08, 2022 9:15:51 AM com.danielfrak.code.keycloak.providers.rest.remote.UserModelFactory create
INFO: Creating user model for: user
giu 08, 2022 9:15:51 AM com.danielfrak.code.keycloak.providers.rest.remote.UserModelFactory create
INFO: Creating user model for: user
giu 08, 2022 9:15:51 AM com.danielfrak.code.keycloak.providers.rest.remote.UserModelFactory create
INFO: Creating user model for: user
giu 08, 2022 9:15:51 AM com.danielfrak.code.keycloak.providers.rest.remote.UserModelFactory create
INFO: Creating user model for: user
giu 08, 2022 9:15:51 AM com.danielfrak.code.keycloak.providers.rest.remote.UserModelFactory create
INFO: Creating user model for: user
giu 08, 2022 9:15:51 AM com.danielfrak.code.keycloak.providers.rest.remote.UserModelFactory lambda$getGroupModel$6
INFO: Found existing group newGroup with id null
giu 08, 2022 9:15:51 AM com.danielfrak.code.keycloak.providers.rest.remote.UserModelFactory create
INFO: Creating user model for: user
giu 08, 2022 9:15:51 AM com.danielfrak.code.keycloak.providers.rest.remote.UserModelFactory create
INFO: Creating user model for: user
giu 08, 2022 9:15:51 AM com.danielfrak.code.keycloak.providers.rest.remote.UserModelFactory create
INFO: Creating user model for: user
[INFO] Tests run: 17, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.279 s - in com.danielfrak.code.keycloak.providers.rest.remote.UserModelFactoryTest
[INFO] Running com.danielfrak.code.keycloak.providers.rest.rest.http.HttpClientTest
[INFO] Tests run: 26, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.754 s - in com.danielfrak.code.keycloak.providers.rest.rest.http.HttpClientTest
[INFO] Running com.danielfrak.code.keycloak.providers.rest.rest.http.HttpRequestExceptionTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 s - in com.danielfrak.code.keycloak.providers.rest.rest.http.HttpRequestExceptionTest
[INFO] Running com.danielfrak.code.keycloak.providers.rest.rest.http.HttpResponseTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in com.danielfrak.code.keycloak.providers.rest.rest.http.HttpResponseTest
[INFO] Running com.danielfrak.code.keycloak.providers.rest.rest.RestUserServiceTest
[INFO] Tests run: 22, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.55 s - in com.danielfrak.code.keycloak.providers.rest.rest.RestUserServiceTest
[INFO] Running com.danielfrak.code.keycloak.providers.rest.rest.UserPasswordDtoTest
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.003 s <<< FAILURE! - in com.danielfrak.code.keycloak.providers.rest.rest.UserPasswordDtoTest
[ERROR] equalsContract  Time elapsed: 0 s  <<< FAILURE!
java.lang.AssertionError:
EqualsVerifier found a problem in class com.danielfrak.code.keycloak.providers.rest.rest.UserPasswordDto.
-> Unsupported class file major version 61

For more information, go to: https://www.jqno.nl/equalsverifier/errormessages
        at com.danielfrak.code.keycloak.providers.rest.rest.UserPasswordDtoTest.equalsContract(UserPasswordDtoTest.java:28)
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 61
        at com.danielfrak.code.keycloak.providers.rest.rest.UserPasswordDtoTest.equalsContract(UserPasswordDtoTest.java:28)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   LegacyUserTest.testEquals:95 EqualsVerifier found a problem in class com.danielfrak.code.keycloak.providers.rest.remote.LegacyUser.
-> Unsupported class file major version 61

For more information, go to: https://www.jqno.nl/equalsverifier/errormessages
[ERROR]   UserPasswordDtoTest.equalsContract:28 EqualsVerifier found a problem in class com.danielfrak.code.keycloak.providers.rest.rest.UserPasswordDto.
-> Unsupported class file major version 61

For more information, go to: https://www.jqno.nl/equalsverifier/errormessages
[INFO]
[ERROR] Tests run: 106, Failures: 2, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.502 s
[INFO] Finished at: 2022-06-08T09:15:53+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project keycloak-rest-provider: There are test failures.
[ERROR]
[ERROR] Please refer to D:\dev\keycloak-cp-theme\keycloak-user-migration\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

There are a few warnings, but the bigger problem seems to be that `maven-surefire-plugin:2.22.2` doesn't like Java 17.

Again, not a Java guy so I'm stumped. Do I need an older version? Am I good to use the artifacts I find in the `target` directory anyway? Because that would be enough.

Thanks for any help.

**Comment by daniel-frak** [comment]
Hi,

The Java version currently used in this project is Java 11. For future reference, you can look at this line in the `pom.xml` file:
https://github.com/daniel-frak/keycloak-user-migration/blob/f9d51b21de3a975b0b5a5987ef3b041b77704d2e/pom.xml#L11

Let me know if you manage to build the project with Java 11 :)

**Comment by stefanomioli-centropaghe** [comment]
@daniel-frak, my man, you just saved my tail, thank you so much: I grabbed Java 11 and it worked. I didn't think to peek into `pom.xml`.

Just to double check: I'm supposed to copy `target\keycloak-rest-provider-1.0-SNAPSHOT.jar` to `/opt/keycloak/providers/app.jar`, right?

Again thank you very much.

**Comment by daniel-frak** [comment]
Glad to have helped :)

That's correct. For Keycloak 18, you just need to copy the jar to the `providers` folder, wherever Keycloak is installed - the `jar` file name shouldn't really matter btw. You'll know it worked if you see `User Migration using a REST client` in the dropdown in Keycloak's `User Federation` tab.

For older versions of Keycloak the folder was `standalone/deployments` (but the newest version of this plugin might not work correctly with them anymore, see `README.md`).

I'm closing this issue for now. Let me know if you encounter any other problems.

**Comment by stefanomioli-centropaghe** [comment]
Thank you very much for all the clarifications, they're really helpful! Have a nice day :)
