### ISSUE TITLE
Migration error / issues after we updated to Keycloak 18 and later 19

### ISSUE THREAD

**Issue by swc-kdzekov** [daniel-frak/keycloak-user-migration#67]
Hello,

Recently we noticed an issue migrating our users to keycloak using the plugin. Namely, on the first attempt the migration fails with a message: _"Unexpected error when handling authentication request to identity provider"_ . The Keycloak log shows that the database, h2, is crashed (you can see the log). This is however temporary. Then, on the second attempt, after a reload of the login page, when the user gives again the credentials, logs in, he/she gets migrated.

What I can say currently is that when we developed the migration client we were using KC 16/17 and everything was fine. 
The problem appeared probably after KC upgrade to version 18, and now for the version 19 still exists.
We are updating the version of the plugin accordingly, so that part as a possible reason is ruled out.

Does anyone have an idea what may be the reason behind the Db crash? And how could we possibly fix this?

Thanks in advance,
Konstantin

[KC18_log_002 (1).txt](https://github.com/daniel-frak/keycloak-user-migration/files/9844310/KC18_log_002.1.txt)

**Comment by swc-kdzekov** [comment]
Extracted stack trace from the log file:

2022-10-24 10:35:46,532 INFO  [org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl] (executor-thread-0) HHH000010: On release of batch it still contained JDBC statements
2022-10-24 10:35:46,536 WARN  [org.keycloak.utils.ServicesUtils] (executor-thread-0) Execution with object [com.danielfrak.code.keycloak.providers.rest.LegacyProvider@51d99187] exceeded specified time limit 3000. 
2022-10-24 10:35:46,536 WARN  [org.keycloak.services] (executor-thread-0) KC-SERVICES0013: Failed authentication: org.keycloak.models.ModelException: javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not execute statement
	at org.keycloak.connections.jpa.PersistenceExceptionConverter.convert(PersistenceExceptionConverter.java:84)
	at org.keycloak.connections.jpa.PersistenceExceptionConverter.invoke(PersistenceExceptionConverter.java:62)
	at com.sun.proxy.$Proxy75.flush(Unknown Source)
	at org.keycloak.models.jpa.UserAdapter.grantRoleImpl(UserAdapter.java:460)
	at org.keycloak.models.jpa.UserAdapter.grantRole(UserAdapter.java:452)
	at org.keycloak.models.jpa.JpaUserProvider.addUser(JpaUserProvider.java:117)
	at org.keycloak.models.jpa.JpaUserProvider.addUser(JpaUserProvider.java:136)
	at com.danielfrak.code.keycloak.providers.rest.remote.UserModelFactory.create(UserModelFactory.java:60)
	at com.danielfrak.code.keycloak.providers.rest.LegacyProvider.lambda$getUserModel$1(LegacyProvider.java:53)
	at java.base/java.util.Optional.map(Optional.java:265)
	at com.danielfrak.code.keycloak.providers.rest.LegacyProvider.getUserModel(LegacyProvider.java:53)
	at com.danielfrak.code.keycloak.providers.rest.LegacyProvider.getUserByUsername(LegacyProvider.java:48)
	at org.keycloak.storage.user.UserLookupProvider.getUserByUsername(UserLookupProvider.java:60)
	at org.keycloak.storage.UserStorageManager.lambda$getUserByUsername$12(UserStorageManager.java:298)
	at org.keycloak.utils.ServicesUtils.lambda$timeBoundOne$1(ServicesUtils.java:83)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:400)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:503)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.keycloak.storage.UserStorageManager.getUserByUsername(UserStorageManager.java:298)
	at org.keycloak.models.cache.infinispan.UserCacheSession.getUserByUsername(UserCacheSession.java:259)
	at org.keycloak.models.utils.KeycloakModelUtils.findUserByNameOrEmail(KeycloakModelUtils.java:228)
	at org.keycloak.authentication.authenticators.browser.AbstractUsernameFormAuthenticator.getUserFromForm(AbstractUsernameFormAuthenticator.java:188)
	at org.keycloak.authentication.authenticators.browser.AbstractUsernameFormAuthenticator.getUser(AbstractUsernameFormAuthenticator.java:167)
	at org.keycloak.authentication.authenticators.browser.AbstractUsernameFormAuthenticator.validateUserAndPassword(AbstractUsernameFormAuthenticator.java:148)
	at org.keycloak.authentication.authenticators.browser.UsernamePasswordForm.validateForm(UsernamePasswordForm.java:55)
	at org.keycloak.authentication.authenticators.browser.UsernamePasswordForm.action(UsernamePasswordForm.java:48)
	at org.keycloak.authentication.DefaultAuthenticationFlow.processAction(DefaultAuthenticationFlow.java:169)
	at org.keycloak.authentication.AuthenticationProcessor.authenticationAction(AuthenticationProcessor.java:990)
	at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:321)
	at org.keycloak.services.resources.LoginActionsService.processAuthentication(LoginActionsService.java:292)
	at org.keycloak.services.resources.LoginActionsService.authenticate(LoginActionsService.java:276)
	at org.keycloak.services.resources.LoginActionsService.authenticateForm(LoginActionsService.java:349)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:380)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:358)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:71)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not execute statement
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188)
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1406)
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1389)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.keycloak.connections.jpa.PersistenceExceptionConverter.invoke(PersistenceExceptionConverter.java:60)
	... 88 more
Caused by: org.hibernate.exception.GenericJDBCException: could not execute statement
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:200)
	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:46)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3375)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3908)
	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:107)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604)
	at org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:478)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:475)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:344)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:40)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:107)
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1402)
	... 94 more
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: Reading from nio:/Users/dzekovk/poolparty/auth_service/keycloak/data/h2/keycloakdb.mv.db failed; file length -1 read length 768 at 1131787 [1.4.197/1]"; SQL statement:
insert into USER_ROLE_MAPPING (ROLE_ID, USER_ID) values (?, ?) [50000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:307)
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:736)
	at org.h2.command.dml.Insert.insertRows(Insert.java:182)
	at org.h2.command.dml.Insert.update(Insert.java:134)
	at org.h2.command.CommandContainer.update(CommandContainer.java:102)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:199)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:153)
	at io.agroal.pool.wrapper.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:88)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
	... 106 more
Caused by: java.lang.IllegalStateException: Reading from nio:/Users/dzekovk/poolparty/auth_service/keycloak/data/h2/keycloakdb.mv.db failed; file length -1 read length 768 at 1131787 [1.4.197/1]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:870)
	at org.h2.mvstore.DataUtils.readFully(DataUtils.java:417)
	at org.h2.mvstore.FileStore.readFully(FileStore.java:98)
	at org.h2.mvstore.Page.read(Page.java:181)
	at org.h2.mvstore.MVStore.readPage(MVStore.java:1936)
	at org.h2.mvstore.MVMap.readPage(MVMap.java:698)
	at org.h2.mvstore.Page.getChildPage(Page.java:208)
	at org.h2.mvstore.Cursor.min(Cursor.java:129)
	at org.h2.mvstore.Cursor.hasNext(Cursor.java:36)
	at org.h2.mvstore.db.TransactionStore$TransactionMap$1.fetchNext(TransactionStore.java:1432)
	at org.h2.mvstore.db.TransactionStore$TransactionMap$1.<init>(TransactionStore.java:1428)
	at org.h2.mvstore.db.TransactionStore$TransactionMap.keyIterator(TransactionStore.java:1423)
	at org.h2.mvstore.db.TransactionStore$TransactionMap.keyIterator(TransactionStore.java:1411)
	at org.h2.mvstore.db.TransactionStore$TransactionMap.ceilingKey(TransactionStore.java:1353)
	at org.h2.mvstore.db.MVSecondaryIndex.requireUnique(MVSecondaryIndex.java:231)
	at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:202)
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:732)
	... 114 more
Caused by: java.nio.channels.ClosedByInterruptException
	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:199)
	at java.base/sun.nio.ch.FileChannelImpl.endBlocking(FileChannelImpl.java:162)
	at java.base/sun.nio.ch.FileChannelImpl.readInternal(FileChannelImpl.java:822)
	at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:802)
	at org.h2.store.fs.FileNio.read(FilePathNio.java:74)
	at org.h2.mvstore.DataUtils.readFully(DataUtils.java:403)
	... 129 more

**Comment by swc-kdzekov** [comment]
2022-10-24 10:35:46,565 WARN  [com.arjuna.ats.jta] (executor-thread-0) ARJUNA016045: attempted rollback of < formatId=131077, gtrid_length=35, bqual_length=36, tx_uid=0:ffffc0a88a51:c6f2:63564dcf:133, node_name=quarkus, branch_uid=0:ffffc0a88a51:c6f2:63564dcf:137, subordinatenodename=null, eis_name=0 > (io.agroal.narayana.BaseXAResource@287a9e91) failed with exception code ARJUNA016099: Unknown error code:0: javax.transaction.xa.XAException: General error: "java.lang.IllegalStateException: This store is closed [1.4.197/4]"; SQL statement:
ROLLBACK [50000-197]
	at org.h2.jdbcx.JdbcXAConnection.convertException(JdbcXAConnection.java:389)
	at org.h2.jdbcx.JdbcXAConnection.rollback(JdbcXAConnection.java:276)
	at io.agroal.narayana.BaseXAResource.rollback(BaseXAResource.java:129)
	at com.arjuna.ats.internal.jta.resources.arjunacore.XAResourceRecord.topLevelAbort(XAResourceRecord.java:362)
	at com.arjuna.ats.arjuna.coordinator.BasicAction.doAbort(BasicAction.java:3037)
	at com.arjuna.ats.arjuna.coordinator.BasicAction.doAbort(BasicAction.java:3016)
	at com.arjuna.ats.arjuna.coordinator.BasicAction.Abort(BasicAction.java:1679)
	at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.cancel(TwoPhaseCoordinator.java:124)
	at com.arjuna.ats.arjuna.AtomicAction.abort(AtomicAction.java:186)
	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.rollbackAndDisassociate(TransactionImple.java:1377)
	at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.rollback(BaseTransaction.java:145)
	at io.quarkus.narayana.jta.runtime.CDIDelegatingTransactionManager.rollback(CDIDelegatingTransactionManager.java:133)
	at org.keycloak.transaction.JtaTransactionWrapper.rollback(JtaTransactionWrapper.java:102)
	at org.keycloak.services.DefaultKeycloakTransactionManager.rollback(DefaultKeycloakTransactionManager.java:182)
	at org.keycloak.services.DefaultKeycloakTransactionManager.rollback(DefaultKeycloakTransactionManager.java:176)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.close(QuarkusRequestFilter.java:127)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$configureEndHandler$2(QuarkusRequestFilter.java:95)
	at io.vertx.ext.web.impl.RoutingContextImpl.lambda$null$0(RoutingContextImpl.java:545)
	at io.vertx.ext.web.impl.SparseArray.forEachInReverseOrder(SparseArray.java:40)
	at io.vertx.ext.web.impl.RoutingContextImpl.lambda$getHeadersEndHandlers$1(RoutingContextImpl.java:545)
	at io.vertx.core.http.impl.Http1xServerResponse.prepareHeaders(Http1xServerResponse.java:707)
	at io.vertx.core.http.impl.Http1xServerResponse.end(Http1xServerResponse.java:411)
	at io.vertx.core.http.impl.Http1xServerResponse.end(Http1xServerResponse.java:391)
	at io.quarkus.resteasy.runtime.standalone.VertxBlockingOutput.write(VertxBlockingOutput.java:91)
	at io.quarkus.resteasy.runtime.standalone.VertxHttpResponse.writeBlocking(VertxHttpResponse.java:172)
	at io.quarkus.resteasy.runtime.standalone.VertxOutputStream.close(VertxOutputStream.java:126)
	at org.jboss.resteasy.util.CommitHeaderAsyncOutputStream.close(CommitHeaderAsyncOutputStream.java:80)
	at io.quarkus.resteasy.runtime.standalone.VertxHttpResponse.finish(VertxHttpResponse.java:145)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:170)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:380)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:358)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:71)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: This store is closed [1.4.197/4]"; SQL statement:
ROLLBACK [50000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:307)
	at org.h2.command.Command.executeUpdate(Command.java:274)
	at org.h2.jdbc.JdbcConnection.rollbackInternal(JdbcConnection.java:1558)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:518)
	at org.h2.jdbcx.JdbcXAConnection.rollback(JdbcXAConnection.java:272)
	... 53 more
Caused by: java.lang.IllegalStateException: This store is closed [1.4.197/4]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:870)
	at org.h2.mvstore.MVStore.checkOpen(MVStore.java:2396)
	at org.h2.mvstore.MVStore.getMapName(MVStore.java:2453)
	at org.h2.mvstore.MVMap.getName(MVMap.java:907)
	at org.h2.mvstore.db.TransactionStore$1.fetchNext(TransactionStore.java:581)
	at org.h2.mvstore.db.TransactionStore$1.<init>(TransactionStore.java:555)
	at org.h2.mvstore.db.TransactionStore.getChanges(TransactionStore.java:549)
	at org.h2.mvstore.db.TransactionStore$Transaction.getChanges(TransactionStore.java:841)
	at org.h2.engine.Session.rollbackTo(Session.java:811)
	at org.h2.engine.Session.rollback(Session.java:776)
	at org.h2.command.dml.TransactionCommand.update(TransactionCommand.java:49)
	at org.h2.command.CommandContainer.update(CommandContainer.java:102)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	... 56 more
Caused by: java.lang.IllegalStateException: Reading from nio:/Users/dzekovk/poolparty/auth_service/keycloak/data/h2/keycloakdb.mv.db failed; file length -1 read length 1024 at 7264238 [1.4.197/1]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:870)
	at org.h2.mvstore.DataUtils.readFully(DataUtils.java:417)
	at org.h2.mvstore.FileStore.readFully(FileStore.java:98)
	at org.h2.mvstore.Page$PageChildren.read(Page.java:1055)
	at org.h2.mvstore.MVStore.readPageChunkReferences(MVStore.java:1356)
	at org.h2.mvstore.MVStore.collectReferencedChunks(MVStore.java:1301)
	at org.h2.mvstore.MVStore.collectReferencedChunks(MVStore.java:1306)
	at org.h2.mvstore.MVStore.collectReferencedChunks(MVStore.java:1286)
	at org.h2.mvstore.MVStore.freeUnusedChunks(MVStore.java:1248)
	at org.h2.mvstore.MVStore.freeUnusedIfNeeded(MVStore.java:1238)
	at org.h2.mvstore.MVStore.storeNowTry(MVStore.java:1025)
	at org.h2.mvstore.MVStore.storeNow(MVStore.java:1016)
	at org.h2.mvstore.MVStore.commitAndSave(MVStore.java:1005)
	at org.h2.mvstore.MVStore.writeInBackground(MVStore.java:2477)
	at org.h2.mvstore.MVStore$BackgroundWriterThread.run(MVStore.java:2713)
Caused by: java.nio.channels.ClosedChannelException
	at java.base/sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:150)
	at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:796)
	at org.h2.store.fs.FileNio.read(FilePathNio.java:74)
	at org.h2.mvstore.DataUtils.readFully(DataUtils.java:403)
	... 13 more

**Comment by swc-kdzekov** [comment]
The problem seems to get fixed by running KC on Postgres Db instead of H2.

**Comment by daniel-frak** [comment]
I don't really have an idea why that could be happening at the moment :(
I anticipate that #68 will be merged soon, so I'm kind of hoping the problem will go away on its own in Keycloak 20...

**Comment by daniel-frak** [comment]
@swc-kdzekov could you confirm if the problem persists in Keycloak 20 with the new version of the plugin?

**Comment by swc-kdzekov** [comment]
@daniel-frak yes, I will check and write latest by Monday.

**Comment by swc-kdzekov** [comment]
Hello @daniel-frak , It seems that the migration is fine on KC 20 with the latest version of the plugin.

**Comment by daniel-frak** [comment]
Great!
