### ISSUE TITLE
Error in using federation

### ISSUE THREAD

**Issue by Thavarajan** [daniel-frak/keycloak-user-migration#73]
Good evening all,
First of all thanks for the wonderful plugin, which is what we exactly needed right now, 
when we try to install this plugin in our existing keycloak we get the following error, can someone guide me the right direction what am i doing wrong

```
2022-12-22 14:55:24,695 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-586) Uncaught server error: java.lang.NoSuchMethodError: 'java.lang.String org.keycloak.common.util.Encode.urlEncode(java.lang.String)'
	at com.danielfrak.code.keycloak.providers.rest.rest.RestUserService.findLegacyUser(RestUserService.java:73)
	at com.danielfrak.code.keycloak.providers.rest.rest.RestUserService.findByUsername(RestUserService.java:67)
	at com.danielfrak.code.keycloak.providers.rest.LegacyProvider.lambda$getUserByUsername$3(LegacyProvider.java:155)
	at com.danielfrak.code.keycloak.providers.rest.LegacyProvider.getUserModel(LegacyProvider.java:51)
	at com.danielfrak.code.keycloak.providers.rest.LegacyProvider.getUserByUsername(LegacyProvider.java:155)
	at org.keycloak.storage.UserStorageManager.lambda$getUserByUsername$16(UserStorageManager.java:334)
	at org.keycloak.utils.ServicesUtils.lambda$timeBoundOne$1(ServicesUtils.java:84)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:400)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:503)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)

```

**Comment by bralandealmeida** [comment]
How did you install Keycloak? With Docker? Could you give details? 

From the message, apparently, you need to configure the module. Did you get to do it?

**Comment by DelanoDuarte** [comment]
> How did you install Keycloak? With Docker? Could you give details?
> 
> From the message, apparently, you need to configure the module. Did you get to do it?

try to use the URL encoder from java.net

`
URLEncoder.encode(usernameOrEmail, StandardCharsets.UTF_8)
`

**Comment by Thavarajan** [comment]
Thank you @DelanoDuarte, @bralandealmeida 

 The problem we are facing is we try to login a space enabled username, it was identified later, now restrict the username without space, though i am not familiar with java we try to use this as our common login app. 

After all odds,now we have some security concerns, while we use this app under our predefined mod_security rules, 
we were not able to update our theme and a few other operations in keycloak, is that an expected scenario or do we need to disable some rule in mod security, 
if we need to disable some mod_security rules, is there any particular reasons for that, since it's a login based app our seniors expect the reason for the rule deactivation, 
kindly suggest

**Comment by Thavarajan** [comment]
yes later we identified the rood cause was due to different versions of keycloak and plugin
